'use client';

import React, { useState } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { toast } from 'sonner';
import { getInvoicePdf, sendInvoiceWhatsApp, Invoice } from '@/lib/api/invoices';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { 
  Share2, 
  Copy, 
  FileText, 
  Send, 
  Phone, 
  Download, 
  Loader2, 
  Sparkles, 
  Check,
  ExternalLink
} from 'lucide-react';

interface InvoiceShareSheetProps {
  invoice: Invoice;
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
}

export function InvoiceShareSheet({ invoice, isOpen, onOpenChange }: InvoiceShareSheetProps) {
  const [phone, setPhone] = useState(invoice.customer?.phone || '');
  const [copied, setCopied] = useState(false);

  // Query to fetch PDF URL when the sheet is open
  const { data: pdfData, isLoading: loadingPdf, error: pdfError } = useQuery({
    queryKey: ['invoice', invoice.id, 'pdf'],
    queryFn: () => getInvoicePdf(invoice.id),
    enabled: isOpen,
    staleTime: 10 * 60 * 1000, // 10 minutes cache
  });

  const pdfUrl = pdfData?.data?.signedUrl;

  // WhatsApp send mutation
  const whatsappMutation = useMutation({
    mutationFn: () => sendInvoiceWhatsApp(invoice.id, phone || undefined),
    onSuccess: (res) => {
      if (res.success) {
        toast.success(`Invoice WhatsApp sandesh safaltapurvak bheja gaya!`);
      } else {
        toast.error('WhatsApp message bhejne mein samasya aayi.');
      }
    },
    onError: (err: any) => {
      toast.error(err.message || 'WhatsApp integration error.');
    },
  });

  const handleCopyLink = () => {
    const link = `${window.location.origin}/invoices/${invoice.id}`;
    navigator.clipboard.writeText(link);
    setCopied(true);
    toast.success('Invoice link clipboard par copy ho gaya!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleWhatsAppSend = (e: React.FormEvent) => {
    e.preventDefault();
    if (!phone) {
      toast.error('WhatsApp number likhna anivary hai!');
      return;
    }
    whatsappMutation.mutate();
  };

  return (
    <Sheet open={isOpen} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-md p-6 bg-card border-l overflow-y-auto">
        <SheetHeader className="border-b pb-4">
          <SheetTitle className="text-base font-extrabold text-foreground uppercase tracking-wider flex items-center">
            <Share2 className="h-5 w-5 text-indigo-400 mr-2" /> Share Invoice (Bheinjein)
          </SheetTitle>
          <SheetDescription className="text-xs font-semibold text-muted-foreground mt-1">
            Grahak ke sath invoice share karne ke tarike chunein.
          </SheetDescription>
        </SheetHeader>

        <div className="space-y-6 pt-5">
          {/* Quick Copy Link Utility */}
          <div className="space-y-2">
            <Label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
              Public Share Link
            </Label>
            <div className="flex space-x-2">
              <Input
                readOnly
                value={`${window.location.origin}/invoices/${invoice.id}`}
                className="h-10 text-xs font-semibold bg-muted/40 border-border/60 text-muted-foreground truncate select-all"
              />
              <Button
                size="icon"
                onClick={handleCopyLink}
                className="h-10 w-10 shrink-0 bg-indigo-600 hover:bg-indigo-700 text-white"
              >
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          {/* PDF Download Trigger */}
          <div className="p-4 rounded-xl border border-border/40 bg-muted/10 space-y-3.5">
            <div className="flex items-start justify-between">
              <div className="space-y-0.5">
                <h4 className="text-xs font-extrabold text-foreground flex items-center uppercase tracking-wider">
                  <FileText className="h-4 w-4 text-indigo-400 mr-1.5" /> PDF Pathra (Download)
                </h4>
                <p className="text-[10px] text-muted-foreground font-medium">
                  Tax-compliant A4 PDF format generated by server
                </p>
              </div>
            </div>

            {loadingPdf ? (
              <Button disabled variant="outline" className="w-full h-9 font-bold text-xs uppercase">
                <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> Generating Secure PDF...
              </Button>
            ) : pdfError ? (
              <p className="text-[10px] font-bold text-destructive">PDF generated failed. Please try again later.</p>
            ) : pdfUrl ? (
              <div className="flex gap-2">
                <Button
                  asChild
                  variant="outline"
                  className="w-1/2 h-9 font-bold text-xs uppercase"
                >
                  <a href={pdfUrl} target="_blank" rel="noopener noreferrer">
                    <ExternalLink className="h-3.5 w-3.5 mr-1.5" /> View PDF
                  </a>
                </Button>
                <Button
                  asChild
                  className="w-1/2 h-9 font-bold text-xs uppercase bg-indigo-600 hover:bg-indigo-700 text-white"
                >
                  <a href={pdfUrl} download={`Invoice-${invoice.invoiceNumber}.pdf`}>
                    <Download className="h-3.5 w-3.5 mr-1.5" /> Download
                  </a>
                </Button>
              </div>
            ) : null}
          </div>

          {/* WhatsApp Direct Integration */}
          <div className="p-4 rounded-xl border border-border/40 bg-muted/10 space-y-3">
            <div className="space-y-0.5">
              <h4 className="text-xs font-extrabold text-emerald-500 flex items-center uppercase tracking-wider">
                <Send className="h-4 w-4 mr-1.5" /> WhatsApp Sandbox Sandesh
              </h4>
              <p className="text-[10px] text-muted-foreground font-medium">
                Send an automated PDF reminder directly to customer's WhatsApp
              </p>
            </div>

            <form onSubmit={handleWhatsAppSend} className="space-y-3.5 pt-1.5">
              <div className="space-y-1.5">
                <Label htmlFor="whatsapp-phone" className="text-xs font-bold text-muted-foreground uppercase tracking-wider flex items-center">
                  <Phone className="h-3 w-3 mr-1 text-emerald-500" /> WhatsApp Number *
                </Label>
                <Input
                  id="whatsapp-phone"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder="e.g. +919876543210"
                  className="h-10 text-xs border-border/60 bg-transparent font-semibold"
                />
              </div>

              <div className="flex gap-2">
                <Button
                  type="submit"
                  disabled={whatsappMutation.isPending}
                  className="w-full h-9 font-bold text-xs uppercase bg-emerald-600 hover:bg-emerald-700 text-white shadow-lg shadow-emerald-500/20"
                >
                  {whatsappMutation.isPending ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> Sending WhatsApp...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-3.5 w-3.5 mr-1.5 animate-pulse" /> Send via WhatsApp
                    </>
                  )}
                </Button>
              </div>
            </form>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}
